dependency:
  name: galaxy
  options:
    ignore-certs: true
    ignore-errors: true
    role-file: molecule/default/requirements.yml
driver:
  name: docker
platforms:
  - name: "${MOLECULE_DISTRO:-centos7}"
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  options:
    vvv: true
verifier:
  name: ansible
  options:
    vvv: true
  inventory:
    all:
      ceph: []