---

- name: Verify
  hosts: all
  strategy: free
  tasks:
    - name: Assert something
      ansible.builtin.assert:
        that:
          - "{{ 1 == 1 }}"
        success_msg: "Assertion is true"
        fail_msg: "Assertion is false"
