name: Tag on Merge

on:
  push:
    branches: [ main ]

env:
  CI: true

jobs:
  tag:
    name: Tag Role
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: minor
